### PR TITLE
Fixing python example tpyos.

### PR DESCRIPTION
**Pull request by hekaldama**
Hope this ins't annoying :).

### CODE REVIEW

**Comment by natefinch** [comment]
No way, I love PRs :)   FWIW, initialise is the UK spelling... but since I'm not in the UK, I definitely accept the change to US English ;)

**Comment by hekaldama** [comment]
Funny. I always spell gray as grey!

**Comment by hekaldama** [comment]
Should I just keep adding doc changes / typo changes here or start new PRs?

**Comment by natefinch** [comment]
Whatever is easiest for you.  I merged this PR, so you'll need a new one, though.

**Pull request merged**
